[skip ci] work in progress 7

diff --git a/.github/workflows/destroy.yaml b/.github/workflows/destroy.yaml
--- a/.github/workflows/destroy.yaml
+++ b/.github/workflows/destroy.yaml
@@ -128,6 +128,7 @@ jobs:
         shell: bash
         run: |
           set -euo pipefail
+          terraform destroy -auto-approve || (echo "==== DESTROY FAILED ====" && exit 1)
           terraform plan -destroy -out=tfdestroy
           terraform show -json tfdestroy > tfdestroy.json
 
@@ -144,6 +145,7 @@ jobs:
         shell: bash
         run: |
           set -euo pipefail
+          terraform destroy -auto-approve || (echo "==== DESTROY FAILED ====" && exit 1)
           terraform destroy -auto-approve
 
       - name: Destroy Summary
